const HEROIMAGES = [
    {"img": require("./a-1.jpeg")},
    {"img": require("./a-2.jpeg")},
    {"img": require("./a-3.jpeg")},
    {"img": require("./a-4.jpeg")},
    {"img": require("./a-5.jpeg")},
    {"img": require("./a-6.jpeg")},
    {"img": require("./a-7.jpeg")},
    {"img": require("./image-asset (0).jpeg")},
    {"img": require("./image-asset (1).jpeg")},
    {"img": require("./image-asset (2).jpeg")},
    {"img": require("./image-asset (3).jpeg")},
    {"img": require("./image-asset (4).jpeg")},
    {"img": require("./image-asset (5).jpeg")},
    {"img": require("./image-asset (6).jpeg")},
    {"img": require("./image-asset (7).jpeg")},
    {"img": require("./image-asset (8).jpeg")},
    {"img": require("./image-asset (9).jpeg")},
    {"img": require("./image-asset (10).jpeg")},
    {"img": require("./image-asset (11).jpeg")},
    {"img": require("./image-asset (12).jpeg")},
    {"img": require("./image-asset (13).jpeg")},
    {"img": require("./image-asset (14).jpeg")},
    {"img": require("./image-asset (15).jpeg")},
    {"img": require("./image-asset (16).jpeg")},
    {"img": require("./image-asset (17).jpeg")},
    {"img": require("./image-asset (18).jpeg")},
    {"img": require("./image-asset (19).jpeg")},
    {"img": require("./image-asset (20).jpeg")},
    {"img": require("./image-asset (21).jpeg")},
]

export default HEROIMAGES